id: xdr0001
name: http日志解析规则
vendor: XDR
worker: 3
inputs: {}
filters:
    - Date:
        src: timestamp
        target: time_generate
#       location: Asia/Shanghai
        add_year: false
        overwrite: true
        formats:
            - '2006-01-02T15:04:05.000000+0000'
#    remove_fields: ["time_occur", "time_save"]  [time_occur][time_save]
    - Rename:
          fields:
              serial_num: observer_serial
              src_ip: sip
              dest_ip: dip
              dest_port: dport
              src_port: sport
              protocol: proto_version
              app_proto: proto
              proto: proto4
              timestamp: time_occur
              event_type: xdr_log_type
    - Add:
        fields:
            time_occur: '[time_generate]'
            observer_vendor: 未来智安
            observer_type: NDR
            observer_product: NDR
            observer_app: 协议识别应用
            observer_appver: '1.0'
            observer_module: WEB解析模块
            log_category: net-log
            log_type: http_proto
            host_original: '[host]'
            primary_key_time: '[time_generate]'
    - Filters:
          if:
              - 'EQ(xdr_log_type,"http")'
          filters:
              - Rename:
                    fields:
                        response_headers: rsp_head
                        req_content_type: content_type
                        request_headers: req_head
                        agent: ua
                        uri: url
                        status: status_code
                        setcookie: set_cookie
                        uri_md5: url_md5
              - Convert:
                    fields:
                        status_code:
                            to: int
                        dport:
                            to: int
                        sport:
                            to: int

outputs: {}