id: ndr0001
name: ndr流量统计
vendor: NDR
worker: 1
inputs:
  - Shm:
      shm_key: 222222
      codec: json
      decorate_events: false
      messages_queue_length: 10
filters:
  - Remove:
      fields: ['@timestamp']
outputs:
  - RedisPub:
      addr: 127.0.0.1:6379
      passwd: ""
      db: 0
      channel: "ndrStats"
      pool_size: 3
