id: xdr0001
name: http日志解析规则
vendor: XDR
worker: 3
inputs:
    - Kafka:
          topic:
              wlza_ndr_http_log: 2
          codec: json
          consumer_settings:
              bootstrap.servers: "10.1.1.11"
              group.id: gohangout.ndrlog-wlza-http
              max.partition.fetch.bytes: '20485760'
              auto.commit.interval.ms: '1000'
              messages_queue_length: 100
              from.beginning: 'false'
filters:
    - Date:
        src: timestamp
        target: time_generate
#       location: Asia/Shanghai
        add_year: false
        overwrite: true
        formats:
            - '2006-01-02T15:04:05.000000+0000'
#    remove_fields: ["time_occur", "time_save"]  [time_occur][time_save]
    - Rename:
          fields:
              serial_num: observer_serial
              src_ip: sip
              dest_ip: dip
              dest_port: dport
              src_port: sport
              protocol: proto_version
              app_proto: proto
              proto: proto4
              timestamp: time_occur
              event_type: xdr_log_type
    - Add:
        fields:
            time_occur: '[time_generate]'
            observer_vendor: 未来智安
            observer_type: NDR
            observer_product: NDR
            observer_app: 协议识别应用
            observer_appver: '1.0'
            observer_module: WEB解析模块
            log_category: net-log
            log_type: http_proto
            host_original: '[host]'
            primary_key_time: '[time_generate]'
    - Filters:
          if:
              - 'EQ(xdr_log_type,"http")'
          filters:
              - Rename:
                    fields:
                        response_headers: rsp_head
                        req_content_type: content_type
                        request_headers: req_head
                        agent: ua
                        uri: url
                        status: status_code
                        setcookie: set_cookie
                        uri_md5: url_md5
              - Convert:
                    fields:
                        status_code:
                            to: int
                        dport:
                            to: int
                        sport:
                            to: int

outputs:
    - Clickhouse:
          table: wlza.xdrlog_wlza_all_fields
          conn_max_life_time: 1800
          username: wlza
          password: clickhouse123!
          bulk_actions: 3000
          flush_interval: 30
          concurrent: 3
          hosts:
              - 'tcp://10.1.1.30:30900'
          fields: ['primary_key_time', 'aa', 'xdr_log_type', 'accept', 'accept_charset', 'accept_encoding', 'accept_language', 'access_mask', 'access_type', 'ac_headers', 'ac_method', 'action', 'action_code', 'affected_asset', 'agent_id', 'alert_category', 'alert_count', 'alert_desc', 'alert_detector', 'alert_group_id', 'alert_id', 'alert_level', 'alert_log_data', 'alert_name', 'alert_response_user', 'alert_seq_id', 'alert_source', 'alert_state', 'alert_type', 'alert_url', 'answers', 'answers_class', 'answers_data', 'answers_data_length', 'answers_name', 'answers_ttl', 'answers_type', 'args', 'assigned_ip', 'attachment', 'attack_method', 'attacker_ip', 'attack_result', 'auth_credentials', 'auth_data', 'auth_orginal', 'auth_sec_result', 'auth_sec_type', 'auth_type', 'auth_vnc_challenge', 'auth_vnc_response', 'bcc', 'bcc_mail', 'cache_control', 'cc', 'cc_mail', 'cert', 'cert_codec', 'chain', 'channel', 'cipher', 'client_app_version', 'client_build', 'client_capabilities', 'client_cert', 'client_cert_codec', 'client_chain', 'client_color_depth', 'client_connection_hint', 'client_desktop_height', 'client_desktop_orientation', 'client_desktop_width', 'client_dialects', 'client_function_keys', 'client_guid', 'client_hassh_algo', 'client_hassh_md5', 'client_id', 'client_ime', 'client_issuer', 'client_ja3', 'client_keyboard_layout', 'client_keyboard_subtype', 'client_keyboard_type', 'client_md5', 'client_name', 'client_not_after', 'client_not_before', 'client_physical_height', 'client_physical_width', 'client_product_id', 'client_realm', 'client_scale_factor', 'client_serial', 'client_server_name', 'client_sha1', 'client_sha256', 'client_sha512', 'client_status', 'client_subject', 'client_version', 'client_warn_desc', 'client_warn_level', 'cmd', 'cmd_data', 'cn', 'cnnvd_id', 'code', 'community_id', 'confidence', 'connection', 'connect_type', 'content', 'content_encoding', 'content_length', 'content_location', 'content_transfer_encoding', 'content_type', 'cookie', 'cookie_count', 'cookie_length', 'curve', 'custom_data', 'cve_id', 'cwd', 'data_model_version', 'date', 'delivery_date', 'dialect', 'dip', 'dip_type', 'disposition', 'dkim', 'dmarc', 'dns_id', 'domain', 'down_bytes', 'down_codec', 'down_payload', 'down_pkts', 'dport', 'dynamic_port', 'encrypted_packet_length', 'encrypt_type', 'error', 'error_code', 'established', 'etag', 'expires', 'ext', 'file_accessed', 'file_attr', 'file_created', 'file_ctime', 'file_guid', 'file_mtime', 'file_name', 'file_size', 'fingerprint', 'flags', 'flow_bytes', 'flow_codec', 'flow_direction', 'flow_duration', 'flow_id', 'flow_payload', 'flow_pkts', 'flow_state', 'fragment', 'from', 'from_mail', 'from_name', 'geo_dip', 'geo_sip', 'header_flags', 'height', 'host', 'host_data', 'host_group', 'host_groupid', 'host_head', 'host_ip', 'host_key_length', 'host_key_type', 'host_md5', 'host_name', 'host_note', 'host_original', 'host_ostype', 'host_tags', 'if_match', 'if_modified_since', 'if_none_match', 'ip_external', 'ip_internal', 'issuer', 'ja3', 'keep_alive', 'kex_first', 'kex_sign', 'kex_sign_length', 'key_algo', 'key_algo_length', 'killchain', 'labels', 'last_modified', 'lease_time', 'length', 'location', 'log_category', 'log_type', 'mac', 'mask', 'md5', 'method', 'mid', 'mime_type', 'mime_version', 'modulus_length', 'msg', 'msg_code', 'msg_id', 'name', 'netbios', 'next_protocal', 'not_after', 'not_before', 'notes', 'observer_app', 'observer_appver', 'observer_module', 'observer_name', 'observer_product', 'observer_serial', 'observer_type', 'observer_vendor', 'opcode', 'origin', 'original_id', 'ou', 'pac', 'password', 'path', 'path_length', 'path_pharse_count', 'pid', 'pixel_format', 'proto', 'proto4', 'proto_version', 'qr', 'query', 'query_class', 'query_count', 'query_length', 'query_name', 'query_type', 'ra', 'range', 'rd', 'received', 'references', 'referer', 'referer_domain', 'reply_received', 'req_body', 'req_body_count', 'req_body_length', 'req_head', 'req_head_count', 'req_head_length', 'req_ip', 'req_lm', 'req_os', 'result', 'result_ip', 'result_original', 'resumed', 'return_path', 'routers', 'rsp_accept_methods', 'rsp_accept_ranges', 'rsp_age', 'rsp_allow_credentials', 'rsp_allow_headers', 'rsp_allow_origin', 'rsp_auth', 'rsp_body', 'rsp_body_length', 'rsp_cache_control', 'rsp_content_encoding', 'rsp_content_language', 'rsp_csp', 'rsp_expose_headers', 'rsp_head', 'rsp_head_count', 'rsp_head_length', 'rsp_lm', 'rsp_max_age', 'rsp_os', 'rsp_range', 'rsp_transfer_encoding', 'rsp_via', 'rule_desc', 'rule_id', 'rule_level', 'rule_name', 'rule_published', 'rule_ref', 'rule_sugg', 'rule_updated', 'rule_version', 'san', 'scheme', 'screen_shared', 'seq_id', 'serial', 'server', 'server_app_version', 'server_guid', 'server_hassh_algo', 'server_hassh_md5', 'server_ip', 'server_key_algo', 'server_key_algo_length', 'server_version', 'service_name', 'service_realm', 'session_id', 'set_cookie', 'set_cookie_count', 'set_cookie_length', 'sha1', 'sha256', 'sha512', 'share_mask', 'share_name', 'share_type', 'sign_id', 'sip', 'sip_type', 'size', 'sni', 'spf', 'sport', 'status', 'status_category', 'status_code', 'status_type', 'sub_cmd', 'subdomain', 'subdomain_length', 'subject', 'tags', 'tc', 'tgt_encrypt_type', 'tgt_md5', 'threat_category', 'threat_type', 'ticket_encrypt_type', 'ticket_md5', 'time_generate', 'time_occur', 'time_save', 'tld', 'to', 'to_mail', 'transfer_encoding', 'trans_id', 'trans_mode', 'tree_id', 'tx_id', 'type', 'ua', 'uid', 'up_bytes', 'up_codec', 'upgrade', 'up_payload', 'up_pks', 'url', 'url_length', 'url_md5', 'url_original', 'url_port', 'user', 'username', 'vendor_class_id', 'via', 'victim_ip', 'vuln_category', 'vuln_type', 'warn_desc', 'warn_level', 'width', 'x509_serials', 'xff', 'x_headers', 'x_headers_length', 'x_mailer', 'x_originating_ip', 'x_spam_level', 'x_spam_status' ]